### ISSUE TITLE
Tracking: Debug Authentication

### ISSUE THREAD

**Issue by labbott** [oxidecomputer/hubris#1492]
Features required for debug authentication on the RoT

Remaining Work

```[tasklist]
### Tasks
- [ ]  #1335
- [ ] Bootleby  Beacon support(?)
- [ ] Generate Debugger key. This needs to be available for signing at the time we are debugging.
- [ ] Review current choices for debug credentials as described in RFD333
- [ ] Sign debug credentials with root key(s). This _must_ be a root key!
```

**Comment by labbott** [comment]
Putting debug authentication testing steps here for reference:
1) Generate a CMPA/CFPA combination that has `debug-auth` set for the appropriate fields. Recommend that the ISP field is kept at `always-enabled` for recovery purposes (unless you like to live dangerously)
2) Generate a debug credential via `lpc55_sign`. Eventually we'll want a way to do this via `permission-slip` as we'll need this to be signed by one of the root keys.
3) run `humility debugmailbox auth-challenge` to spit out a challenge credential
4) run `lpc55_sign debug-response` using the debug credential previously generated and the challenge generated by the previous step. This will generate a signed response
5) run `humility debugmailbox auth-response` with the response from the previous step

The auth response will boot into Hubris
